# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 13:08
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='news')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('announce', models.CharField(blank=True, max_length=255)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
