# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-09 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20160905_1415'),
        ('news', '0002_auto_20160909_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='documents',
            field=models.ManyToManyField(to='documents.Document'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='news'),
        ),
    ]
