# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-09 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20160909_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAdditional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.PositiveSmallIntegerField(default=0)),
                ('views', models.PositiveSmallIntegerField(default=0)),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional', to='news.News')),
            ],
        ),
    ]
