# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='h3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='slider',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='slider',
            name='p',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
