# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('position', models.CharField(max_length=128)),
                ('order', models.PositiveSmallIntegerField()),
                ('category', models.CharField(choices=[('администрация', 'администрация'), ('педагоги', 'педагог'), ('обслуживающий персонал', 'обслуживающий персонал')], max_length=64)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='detail')),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
