# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_category', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('education', models.CharField(max_length=255)),
                ('teach_exp', models.DateField()),
                ('cur_exp', models.DateField()),
                ('training', models.TextField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='phone',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='detail'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='additionalinformation',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='staff.Staff'),
        ),
    ]
