# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20160903_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='sex',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='additionalinformation',
            name='teach_exp',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='order',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
