# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='data',
            new_name='date',
        ),
    ]
