# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base',
            name='fav_icon',
        ),
    ]
