# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 14:11
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speciality',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='area',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='qualification',
        ),
        migrations.AddField(
            model_name='speciality',
            name='text',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='speciality',
            name='code',
            field=models.CharField(max_length=10, verbose_name='код'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='title',
            field=models.CharField(max_length=127, verbose_name='название'),
        ),
    ]
