# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-12 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specialty', '0003_auto_20160912_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speciality',
            old_name='qualification',
            new_name='qualifications',
        ),
    ]
