# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-13 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialty', '0005_auto_20160913_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional',
            name='speciality',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='add', to='specialty.Speciality'),
        ),
    ]
