# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-09 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='тип')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('order',),
            },
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set([]),
        ),
        migrations.CreateModel(
            name='GroupMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('order', models.PositiveSmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.GroupMenu')),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='тип')),
                ('main_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.MainMenu')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='submenu',
            unique_together=set([('main_menu', 'order')]),
        ),
        migrations.AlterUniqueTogether(
            name='mainmenu',
            unique_together=set([('group', 'order')]),
        ),
        migrations.AlterModelOptions(
            name='groupmenu',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='groupmenu',
            name='blank',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_menus', to='menu.GroupMenu'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='main_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_menus', to='menu.MainMenu'),
        ),
        migrations.RemoveField(
            model_name='menu',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='parent',
        ),
        migrations.AlterModelOptions(
            name='submenu',
            options={'ordering': ('order',)},
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
