# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20160712_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='content_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='object_id',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set([('order', 'parent')]),
        ),
    ]
