# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 13:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20160728_0831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmenu',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='groupmenu',
            name='blank',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_menus', to='menu.GroupMenu'),
        ),
        migrations.AlterField(
            model_name='submenu',
            name='main_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_menus', to='menu.MainMenu'),
        ),
    ]
