# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-05 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_auto_20160728_1321'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='menu',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='parent',
        ),
        migrations.AlterModelOptions(
            name='submenu',
            options={'ordering': ('order',)},
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
