# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('detail', '0004_auto_20160706_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.Menu'),
            preserve_default=False,
        ),
    ]
