# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-09 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20160905_1415'),
        ('detail', '0006_remove_detail_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='documents',
            field=models.ManyToManyField(to='documents.Document'),
        ),
    ]
